In [1]:
import numpy as np
import tensorflow as tf

In [2]:
#use numpy for creating vectors

x = np.array([1,2,3,4,5])

In [3]:
x

array([1, 2, 3, 4, 5])

In [4]:
x.T

array([1, 2, 3, 4, 5])

In [5]:
x.shape

(5,)

In [6]:
x.T.shape

(5,)

In [7]:
y = np.array([[1,2,3,4,5]])

In [8]:
y.shape

(1, 5)

In [9]:
y.T.shape

(5, 1)

In [10]:
#zero vectos

z = np.zeros(5)

In [11]:
z

array([0., 0., 0., 0., 0.])

In [12]:
#Using tensorflow

In [13]:
y_tf = tf.Variable([1,2,3,4,5])

In [14]:
y_tf

<tf.Variable 'Variable:0' shape=(5,) dtype=int32, numpy=array([1, 2, 3, 4, 5], dtype=int32)>